### ISSUE TITLE
list items become unresponsive if navigation happens during scroll

### ISSUE THREAD

**Issue by mvayngrib** [software-mansion/react-native-screens#102]
not fixed by fixes for #53

see [snack](https://snack.expo.io/@tmv/ebe266) (based on [this snack](https://snack.expo.io/@oriharel/Y3JlYX), but with an easier repro)

1. tap any rows on the left tab
2. scroll down in the left tab. When `onMomentumScrollBegin` is detected, it will navigate to the 2nd tab. Press `Go Back` to go back
3. list items are no longer tappable

**Comment by jdhorner** [comment]
Note: This snack worked fine for me on the Android preview of the snack, but crashes as described above, in the iOS version of the snack.

**Comment by TalonHughes13** [comment]
I am getting this issue on iOS when upgrading from 1.0.0-alpha.23 to 2.7.0 and using enableScreens(). The removal of enableScreens resolves the issue, but would like to see if there is a better resolution.

**Comment by WoLewicki** [comment]
I debugged it and the problem is basically this.
1. When navigating after the `onMomentumScrollBegin`, the native RCTScrollView is detached along with the `Screen` containing it. 
2. It resolves to `onMomentumScrollEnd` event not being fired from the native side.
3. Because this event is not fired, `ScrollResponder` doesn't fire event: https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L1168
4. Because the event is not fired, the `lastMomentumScrollEndTime ` is not updated: https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollResponder.js#L397
5. It resolves in the calculation of if  the scrollView is animating to true.
6. It makes the content views not being responders to the touch events: https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollResponder.js#L214, which causes the bug.

**Comment by WoLewicki** [comment]
Can you check if #594 fixes this issue?

**Comment by happyfloat** [comment]
@WoLewicki I think I'm also experiencing this issue. Thankfully I found this issue before removing this library, it's clearly a deal breaker for production use!? 

I didn't know it was related to the Lists and already gave up on creating a new Github-Issue to reproduce my "complicated navigation setup/issue". 

I will give your PR a shot soon! Thank you very much 👍

**Comment by WoLewicki** [comment]
Please report here if it works correctly 👍 .

**Comment by happyfloat** [comment]
@WoLewicki I did apply the PR as a patch. So far the issue did not appear again 👍 . I will report back if it happens again.
