### ISSUE TITLE
Compiling issue : No visible @interface for 'RNSScreenStackView' declares the selector 'cancelTouchHandlerIfExists'

### ISSUE THREAD

**Issue by vvdodiya** [software-mansion/react-native-screens#1057]
I have just install lib react-native-screens and pod install. I tried to compiling the project it gives errors : 
No visible @interface for 'RNSScreenStackView' declares the selector 'cancelTouchHandlerIfExists'
here I attached a screenshot.
![Screenshot 2021-08-18 at 12 34 16 PM](https://user-images.githubusercontent.com/24320461/129854268-abf67843-da4c-4fb9-9390-d42c63f4294c.png)

**Comment by kacperkapusciak** [comment]
Hi @vvdodiya,
Thank you for submitting an issue. We are aware of this issue and it will be fixed in the next release (v3.6.0) of `react-native-screens`.
This issue was fixed in https://github.com/software-mansion/react-native-screens/pull/1040
In the meantime, you can apply changes from this PR to your code or install `react-native-screens` directly from the master branch with
```
yarn add git+https://github.com/software-mansion/react-native-screens#master
```
