### ISSUE TITLE
Swipe to go back gesture does not work consistently on iOS 12

### ISSUE THREAD

**Issue by SimpleCreations** [software-mansion/react-native-screens#1091]
## Description

I'm experiencing the exact same issue as described here: #853 
I am able to reproduce it on a physical iPhone 6 running iOS 12.5.4. (I've also tried iOS 14 simulator, where the issue is not present. On iOS 12.4 simulator, the gesture does not work at all.)

Demo:

https://user-images.githubusercontent.com/12449725/131385658-f1761a8c-ee98-4a89-9e12-687902aea1c1.mp4

## Steps To Reproduce

Have a native stack navigator with at least two screens and a way to navigate between them.
Use the swipe to go back gesture.

### Expected behavior

The swipe gesture works consistently.

### Actual behavior

Sometimes the gesture fails to work and a quick flicker can be seen when the top screen moves back to its original place.

## Snack or minimal code example

```typescript
import React from "react";
import { Button } from "react-native";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator, NativeStackScreenProps } from "@react-navigation/native-stack";

type StackParams = {
  Screen: undefined;
  Screen2: undefined;
}

const Stack = createNativeStackNavigator<StackParams>();

const Screen2 = () => {
  return null;
};

const Screen = ({navigation}: NativeStackScreenProps<StackParams>) => (
  <Button title="Go to Screen2" onPress={() => navigation.navigate("Screen2")} />
);

const App = () => (
  <NavigationContainer>
    <Stack.Navigator initialRouteName="Screen">
      <Stack.Screen
        name="Screen"
        component={Screen} />
      <Stack.Screen
        name="Screen2"
        component={Screen2} />
    </Stack.Navigator>
  </NavigationContainer>
);

export default App;
```

## Package versions

- React: 17.0.1
- React Native: 0.64.1
- React Native Screens: 3.6.0

**Comment by kacperkapusciak** [comment]
Hi @SimpleCreations,
First, I'd like to thank you because your issue reports are always of the highest quality and I wish more people would so accurately fill the template with all the information that we need 🥇 

Second, I'm very sorry for not getting to you sooner

but I have some good news for you. We've figured out what caused this issue and a brief explanation could be found in the description of https://github.com/software-mansion/react-native-screens/pull/1150

Could you double-check if this solves the issue for you?

Cheers

**Comment by SimpleCreations** [comment]
@kacperkapusciak thank you for your kind words and for the fix! 
Can confirm that the PR solves the issue.
