### ISSUE TITLE
Android app freezes when navigation back from views

### ISSUE THREAD

**Issue by danidaryaweesh** [software-mansion/react-native-screens#1125]
## Description
Android app freezes when user navigates back in the views. Was able to avoid the issue when I turned of enable screens. I'm using the latest version (3.7.0)

## Steps To Reproduce

1. Go into a view
2. Go back using navigation

### Expected behavior
App should be functional
### Actual behavior
App freezes and never works again

- React: 17.0.1
- React Native: 0.64.2
- React Native Screens: 3.7.0

**Comment by WoLewicki** [comment]
I'm closing this issue due to not following the contributing guidelines for `react-native-screens`. Especially, there is no information about the navigator being used. 

For more information see [contributing guide](https://github.com/software-mansion/react-native-screens/blob/master/guides/CONTRIBUTING.md).
