### ISSUE TITLE
Use mavenCentral() since jcenter is shutting down

### ISSUE THREAD

**Issue by dovandung1165** [software-mansion/react-native-screens#1147]
I noticed a warning in my React Native project when I build it on Android about this library:
```WARNING: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.```
Just want to be helped replace jcenter() from the build script and change to another as jcenter is deprecated and it will be shut down in the future.

**Comment by dovandung1165** [comment]
Ah! It related to another issue. [#1101 ](https://github.com/software-mansion/react-native-screens/pull/1101). I got it.
But do you have any plan to remove jcenter()?

**Comment by kacperkapusciak** [comment]
Hi @dovandung1165,

`jcenter()` was removed from our repo for a few weeks but it had to be added back because lack of it caused an issue - https://github.com/software-mansion/react-native-screens/issues/1092. It seems like some react-native dependencies aren't present in newer maven repositories yet.

`mavenCentral()` is already present in our repo - https://github.com/software-mansion/react-native-screens/blob/master/android/build.gradle#L50 thus making warning about shut down of `jcenter()` completely harmless.

If this warning bothers you a lot you can always use [patch-package](https://github.com/ds300/patch-package#readme) to remove `jcenter()` from your build but we aren't going to do anything about this in the nearest future.

Cheers

**Comment by matteodanelli** [comment]
All dependencies has been moved. jcenter can now be completely removed from the project.
