### ISSUE TITLE
RN <Modal> not working within <FullWindowOverlay>

### ISSUE THREAD

**Issue by d99iel** [software-mansion/react-native-screens#1149]
## Description
The following will result in:
> Exception thrown while executing UI block: Can't present modal view controller without a presenting view controller

## Steps To Reproduce

```
import {Modal, View} from 'react-native'
import { FullWindowOverlay } from 'react-native-screens'
...
        <FullWindowOverlay>
        <Modal animationType='slide' visible={true}>
          <View></View>
        </Modal>
        </FullWindowOverlay>
...
```

### Screenshots
![Simulator Screen Shot - iPhone 11 - 2021-09-22 at 20 04 11](https://user-images.githubusercontent.com/6758064/134398425-2dd4520f-2bbe-4f01-ae9a-bdb0b98a0ca0.png)

### Expected behavior
RN Modal should work as a child in FullWindowOverlay

## Package versions

- React: 17.0.2
- React Native: 0.64.2
- React Native Screens: 3.7.0

**Comment by WoLewicki** [comment]
Yes, it is not possible to render a `Modal` inside `FullWindowOverlay` since it does not have any view controllers in its view hierarchy. Could you tell me what is the use-case of rendering a `Modal` inside this component? It already works kind of like modal by itself.

**Comment by d99iel** [comment]
The use-case is a developer-menu thats always on top in the app. The dev-menu contains <Modals> to  show different stuff, like the app state etc. But i could prob re-engineer this part since it's not a critical part for the end-user. 

Ok, well then it should probably not be considered as a bug. I'll close this one.

**Comment by WoLewicki** [comment]
I believe the modal in the "always on top" component should not be necessary since the modal itself should be something rendered on top of the hierarchy, you can look at https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/modality/ for more information. I might be wrong, but the solution for this would need to be probably e.g. rendering a navigator in the `FullWindowOverlay` to provide a view controller. It might lead to other problems though.
