### ISSUE TITLE
iOS - fullScreenModal not dismissable

### ISSUE THREAD

**Issue by clemensmol** [software-mansion/react-native-screens#1232]
First of all, thank you for this wonderful package!

Using @react-navigation/native-stack you can't dismiss a fullScreenModal with a gesture like 'presentation: modal' does. Don't know if it's a bug or if it's intended but it would be nice to be able to dismiss a fullscreen modal with a swipe down gesture.

iOS 15.1.1

##Presentatin: modal works
https://user-images.githubusercontent.com/5475805/145014756-47519ff8-ede4-4d64-90d5-272de5e7afbe.mp4

##Presentatin: fullScreenModal does not work
https://user-images.githubusercontent.com/5475805/145015313-fe05a71b-b656-49db-a509-946401748bbc.mov

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |   0.66.3     |
| @react-navigation/native               |   6.2.5      |
| @react-navigation/native-stack         |   6.2.5      |
| react-native-screens                   | 3.10.0 |
| react-native-safe-area-context         |   3.3.2      |
| react-native-gesture-handler           |   1.10.3      |
| react-native-reanimated                |    2.2.4     |

**Comment by WoLewicki** [comment]
`fullScreenModal` resolves to [`UIModalPresentationFullScreen`:](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/uimodalpresentationfullscreen?language=objc) https://github.com/software-mansion/react-native-screens/blob/76f4fc62aa5e7c04dba4a623fa0387b2b5b5ccb3/ios/RNSScreen.m#L102. This style of presentation covers the whole screen and is not dismissible. It is intended behavior since that is how `iOS` platform defines it, so nothing can be done about it. Can we help you anymore with this?

**Comment by clemensmol** [comment]
Thank you for your swift response!

Guess I'm gonna have to find another way to modally view some kind of slideview and swipe down to close it. React Animated is just too slow for these interactions.
