### ISSUE TITLE
Can we exclude components on a screen from becoming frozen?

### ISSUE THREAD

**Issue by hannojg** [software-mansion/react-native-screens#1238]
Hey,

I didn't have the time to look too much into the internal works of this library. But I was wondering if there is a possibility to prevent freezing for a component, that is presented on a screen that is currently frozen?

In our use case, we have an XP bar that is synced everywhere (so when you have multiple XP stuff showing on one screen everything is synced). This XP bar runs animation when the XP of the user is changing. The issue is, that when the user comes back to a frozen screen, the XP bar runs its animation, as it just got the new XP data and starts the animation (although we showed the XP progress on a previous screen, so there is no need to show the animation).

Another option would be to maybe skip the whole screen from becoming frozen.

**Comment by ku8ar** [comment]
This mechanism was probably inspired by angular (sic!) ChangeDetectorRef.
Without any additional library, similar effect can be achieved by simply wrapping frequently changing values:

```javascript
// react-freeze replacement where the developer has control over code
const useNavFrozenValue = (value) => {
 const isFocused = useIsFocused()
 const memoizedValue = useMemo(() => value, [isFocused])
 return isFocused ? value : memoizedValue
}

// component with memo
const CountText = memo(({ count }) => <Text>{count}</Text>)

// usage
const FrequentlyChangingComponent = () => {
 const [count, setCount] = useState(0)
 
 useEffect(() => {
   setInterval(() => setCount(count => count + 1), 1000)
 }, [])
  
  return <CountText count={useNavFrozenValue(count)} />
}
```

This approach has an additional advantage: developer is intentionally memoizing values, so freezing itself is not some side-effect from a standalone library, but an intentional action to optimize app. So I suggest just not using react-freeze.
