### ISSUE TITLE
animation is freezing when going back in native stack

### ISSUE THREAD

**Issue by IvanIhnatsiuk** [software-mansion/react-native-screens#1378]
## Description
Animation is freezing when going back in native stack, however on JSStack it still animating

### Screenshots

https://user-images.githubusercontent.com/86000012/160877631-ce472c5c-7902-4606-90a1-66b2baea8f9f.mov

## Steps To Reproduce

1. launch an app
2. go to NativeStack screen
3. go to screen with animation
4. press on go back button
5. see that animation is stopped

### Expected behavior

animations should not be stopped when go back

### Actual behavior

animations are stopped when go back

## Reproduction

https://github.com/IvanIhnatsiuk/Freezing-animation-on-native-stack

## Platform

- [x] iOS
- [x] Android
- [ ] Web
- [ ] Windows
- [ ] tvOS

## Workflow

- [ ] Managed workflow
- [ ] Bare workflow

## Package versions

| package                                | version |
| -------------------------------------- | ------- |
| react-native                           |   0.66.4      |
| @react-navigation/native               |    ^6.0.8     |
| @react-navigation/native-stack         |   ^6.5.2    |
| react-native-screens                   |    ^3.13.1     |
| react-native-safe-area-context         |     ^3.3.2    |
| react-native-gesture-handler           |      ^2.3.2   |
| react-native-reanimated                |    ^2.5.0     |
| react-navigation/stack                |    6.1.1     |

**Comment by WoLewicki** [comment]
It is a result of how those stacks work under the hood. JS stack does not remove React views of the screen being dismissed till the end of the animation. Therefore those views can be animated. In `native-stack`, when you dismiss screen with `navigation.goBack`, React views are removed immediately, and native side handles the dismiss animation. It results in what we can see in the video. If you need to animate something, you should go back with swipe or native header back button since those options first animate the dismiss of screen, and then remove its React views.

On Android, you can use [this prop](https://github.com/software-mansion/react-native-screens/blob/9b4e50ed2085d5fe851398f81e2409d7431d13b1/src/native-stack/types.tsx#L271) to have the same effect as native header back button on iOS.

Can I help you more with this?

**Comment by IvanIhnatsiuk** [comment]
@WoLewicki Yes, you helped. Thank you for your reply!

**Comment by WoLewicki** [comment]
Ok so I am closing this issue. Feel free to comment if there is something wrong and we can always reopen it then.

**Comment by NiccoloCase** [comment]
have you solved this issue?
