### ISSUE TITLE
ViewPropTypes usage

### ISSUE THREAD

**Issue by jbrodriguez** [software-mansion/react-native-screens#1527]
Hi, with RN 0.69.1 (i think it doesn't happen on RN 0.69.0), an app using react-native-screens won't start because of ViewPropTypes was removed from RN

```bash
 ERROR  Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'., js engine: hermes
```

Any thoughts on this ?

**Comment by hirbod** [comment]
Should be pretty urgent considering Expo SDK 46 is already in beta

**Comment by kkafar** [comment]
@jbrodriguez 
I've just created and successfully run fresh app with `react-native@0.69.1` & `react-native-screens@3.15.0` on both architectures. 
Is there any specific setup I need to follow to reproduce this error? I'm sure this is an issue, because of [this commit](https://github.com/facebook/react-native/commit/10199b158138b8645550b5579df87e654213fe42), but how do I trigger it? It would be great if you stick to the issue template.

**Comment by jbrodriguez** [comment]
hi @kkafar, it happened to me a on a fresh app, just starting displayed the red box.

i thought it was something specific to react-native-screens but there are many libraries affected https://github.com/facebook/react-native/issues/33557

**Comment by kkafar** [comment]
@jbrodriguez,
Unfortunately I can't reproduce this. Even if I place in my test example this code explicitly:
```javascript
import {ViewPropTypes} from 'react-native';
```
I don't get any error, although I can clearly see in my `node_modules/react-native/index.js` that I should get one: 
```javascript
...
  get ViewPropTypes(): $FlowFixMe {
    invariant(
      false,
      'ViewPropTypes has been removed from React Native. Migrate to ' +
        "ViewPropTypes exported from 'deprecated-react-native-prop-types'.",
    );
  },
...
```
This is just strange. 

Could you tell me if there is any stack trace included / how do you know that it is `react-native-screens` that cause this issue? I'm asking because, to my best knowledge we don't have place in code where we explicitly import `ViewPropTypes`. We do, however, import from `react-native/Library/Components/View/ViewPropTypes` but these files still exist (on both `main` and `0.69-stable` React Native branches) and should not be causing any issues.

**Comment by jbrodriguez** [comment]
@kkafar yes, that's odd. i remember seeing that react-native-screens was one of the libraries that was still using ViewPropTypes, but in retrospect, i might have misread the logs.

i'm unable to test currently, because i had to move on with a rn patch in order to keep working :)

i'll close this one for the time being and reoopen/open new one if can repro

**Comment by corbt** [comment]
This does seem to still be an issue; when upgrading from RN 0.68 to 0.70 I'm still seeing errors that look like `Invariant Violation: ViewPropTypes has been removed from React Native. Migrate to ViewPropTypes exported from 'deprecated-react-native-prop-types'.`. `react-native-screens` is the only dependency in my tree that still imports `ViewPropTypes` from react-native directly.

**Comment by Avishayy** [comment]
Any update on this? Do you need help with repro? Using ViewPropTypes has been deprecated since 0.68 and causes an error since 0.69. This is the only library I have left that uses this.

**Comment by kkafar** [comment]
I'll look into this, however I would love having a reliable reproduction from you guys, due to [reasons I mentioned earlier](https://github.com/software-mansion/react-native-screens/issues/1527#issuecomment-1194027281)

**Comment by Avishayy** [comment]
@kkafar as to answer "Could you tell me if there is any stack trace included / how do you know that it is react-native-screens that cause this issue?"

There's no stack trace. I know it is react-native-screens because I used to have that warning around 20 times, so I upgraded all my libraries and now I have only one instance of the messafw, I searched for ViewPropTypes in my node_modules and found only relevant usage in this library (the others being react-native itself and deprecated-react-native-prop-types)

You can either start using deprecated-react-native-prop-types or reactor the code, as for repro, I don't think it matters that much because the issue is obvious, but did you try importing it on a new react-native project?

**Comment by kkafar** [comment]
> [...] but did you try importing it on a new react-native project?

Yeah, as I stated [here](https://github.com/software-mansion/react-native-screens/issues/1527#issuecomment-1193391283) I ran it on fresh app (even on two different machines) and it worked just fine as it still does right now. 

> [...] I don't think it matters that much because the issue is obvious [...]

I would argue that it is not (at least with information that was presented so far), because it seems that it is environment dependent (maybe some dependencies conflicts, old cache, who knows what else). 

It would be much easier & quicker if there was a reliable reproduction & information on library  and other dependencies versions that are in use. 

I've prepared potential fix: https://github.com/software-mansion/react-native-screens/pull/1647 , however due to aforementioned reasons I'm not able to test whether it works or not. 

You can check it out by installing `react-native-screens` from `@kkafar/viewproptypes-fix` branch:

```
...
"react-native-screens": "software-mansion/react-native-screens#@kkafar/viewproptypes-fix"
...
```

**Comment by Avishayy** [comment]
Thanks @kkafar 

This is embarrassing to admit but I was wrong, I did actually have another library that caused issue. I was sure it is react-native-screens because I CTRL+F'd references to `ViewPropTypes` and I saw them all in this package but the results shadowed the one result in another package so react-native-screens is fine as is. 

For what it is worth, I took a look at #1647 and tested it (it works), I think importing `ViewProps` immediately from `react-native` is better (as you do have a dependency for `@types/react-native`) and perhaps that commit should be regardless.

Sorry for the hassle and thank you for being helpful and attentive.
