### ISSUE TITLE
`headerTitleAlign: 'center'` causes truncation to occur at incorrect point when `headerRight` is populated on Android

### ISSUE THREAD

**Issue by liamjones** [software-mansion/react-native-screens#1573]
### Description

I initially reported this on the react-navigation repo (https://github.com/react-navigation/react-navigation/issues/10788) but having dug through the code a bit I _think_ the issue is in screens. It looks like react-navigation is basically handing the configuration of this property off to screens to deal with.

### Current behaviour

If you have a `headerRight` populated in a `native-stack` navigator and `headerTitleAlign` is default/`left` the title correctly truncates before the `headerRight` element:

![image](https://user-images.githubusercontent.com/521341/186657580-8499cb04-7144-4bb2-be61-8a93ebeb61c2.png)

However, if you set `headerTitleAlign: 'center'` the text truncation point moves to a *longer* position and it truncates behind the `headerRight` element:

![image](https://user-images.githubusercontent.com/521341/186657423-63881665-b8ca-494d-bd99-33c5b6b5db23.png)

### Expected behaviour

The truncation point shortens so that the title still truncates before running behind the `headerRight` element.

### Steps to reproduce

1. Set a `native-stack` navigator with `headerAlignTitle: 'center'`
2. Setup view with a long title and an item in `headerRight`
3. View on Android

### Snack or a link to a repository

https://snack.expo.dev/@liam/react-navigation-6-headertitlealign-center-bug-on-android

### Screens version

3.15.0

### React Native version

0.69.4 / 0.66.3

### Platforms

Android

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Huawei P30 lite

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @liamjones, thank you for reporting this problem!
Unfortunately, I think this issue is related strictly to the implementation of `headerTitleAlign` that is the part of the react-navigation. We don't currently support changing the position of the title on Android, what may be changed shortly after we merge #1874 - with this change you will be able to specify header with `center-aligned` type that will center the header title. 

As I investigated, it shouldn't cover other parts of the header 🎉 

**Before adding element:**
<img width="674" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/23281839/c6cd0ca9-1656-4f0f-b75f-12c429c63a67">

**After adding element:**
<img width="680" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/23281839/7495b274-4f33-41a4-a58f-844183d287f7">

I'll close this issue for now (and eventually will come up with a solution in react-navigation's issue), but if you're still not happy with current behavior of this prop (or you're still facing this issue after using `center-aligned` header type) don't hesitate to reopen this pull request - we will try to fix it with a pinch of magic (but first of all please make sure this issue doesn't impact react-navigation) 🪄✌️
