### ISSUE TITLE
iOS crash navigating from modal->tab when new architecture is enabled

### ISSUE THREAD

**Issue by curthipster** [software-mansion/react-native-screens#1746]
### Description

Cross-posting https://github.com/react-navigation/react-navigation/issues/11270 at the request of its maintainers.

My navigation hierarchy is:

```
Stack Navigator
|- Tab navigator
| |- Home
| |- Another tab
|- Modal
```

When the modal is open, pressing the text should close the modal and navigate to "Another tab". The code is doing that via `navigation.replace`. When new architecture is enabled, the app crashes on that call.

Below is a video, and a repro is attached.

https://user-images.githubusercontent.com/577293/223592149-7f342d71-a798-40fb-874f-0e33c99f3965.mov

### Steps to reproduce

This works perfectly fine when New Architecture is not enabled:

You can use the attached repo to observe by changing the first line in the Podfile and rebuilding.

```
ENV['RCT_NEW_ARCH_ENABLED'] = "0"
```

Here is a demo:

https://user-images.githubusercontent.com/577293/223591777-4591d48a-3b12-4fdc-bbc2-933724a3a48d.mov

### Snack or a link to a repository

https://github.com/curthipster/ReactNavModalIosCrash

### Screens version

3.20.0

### React Native version

0.71.3

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 14 iOS 16.4

### Acknowledgements

Yes

**Comment by maksg** [comment]
Hey @curthipster, thank you for reporting this bug. Does this issue still occur for you? I've tried your sample but couldn't reproduce it on new architecture. If it does, could you please provide an updated sample, because I couldn't launch it without moving the code to fresh app, so maybe I missed some important setup step?

https://github.com/user-attachments/assets/d07c86aa-79ef-4242-a25a-916973c09451
