### ISSUE TITLE
package="com.swmansion.rnscreens" found in source AndroidManifest.xml

### ISSUE THREAD

**Issue by deiiviidas** [software-mansion/react-native-screens#1770]
### Description

When starting android npx react native server it drops errors - how to fix (app is working normally)

Task :react-native-screens:processDebugManifest
package="com.swmansion.rnscreens" found in source AndroidManifest.xml: C:\Users\dev\Desktop\application\tarprat\n
ode_modules\react-native-screens\android\src\main\AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated.
Please instead set the namespace (or testNamespace) in the module's build.gradle file, as described here: https:
//developer.android.com/studio/build/configure-app-module#set-namespace
This migration can be done automatically using the AGP Upgrade Assistant, please refer to https://developer.andr
oid.com/studio/build/agp-upgrade-assistant for more information.

### Steps to reproduce

npx react-native start

### Snack or a link to a repository

https://stackoverflow.com/help/mcve.

### Screens version

3.20.0

### React Native version

0.71.7

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Android emulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey, thanks for reporting!
This is a warning I'm aware of for some time & It won't be fixed now. 

Basically since AGP 8.0 setting package namespace in manifest file does not have effect & is deprecated, but:

1. Last time I checked React Native CLI (a tool required to run your project) crashes when package namespace is not present in your manifest file.
2. Effectively setting the value there has no effect (besides these warnings).

I'll close this issue, since it does not lead to compilation errors rn.
