### ISSUE TITLE
TR SYSTEM LANGUAGE PROBLEM

### ISSUE THREAD

**Issue by mehmettasan** [software-mansion/react-native-screens#1849]
### Description

After installing the React Navigaton package, I get an error when I try to install this package while the system language is Turkish. When I change the system language to English, it installs without any problems. I am using windows 11 and the operating system is up to date. 
**this screenshot is for react-native-safe-area-context but same problem exists in this package.**
![Ekran görüntüsü_20230728_183744](https://github.com/software-mansion/react-native-screens/assets/83862655/08f01533-ddf5-48ff-9d12-86dcb7c4eeee)

### Steps to reproduce

1- change system language turkish
2- npm install @react-navigation/native
3- npm install react-native-screens react-native-safe-area-context
4- npx react-native run-android

### Snack or a link to a repository

none

### Screens version

3.23.0

### React Native version

0.72.3

### Platforms

Android, Windows

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by mehmettasan** [comment]
> 

i trying with clean project. if you want see this problem you can change your windows language turkish and just run project.

**Comment by mehmettasan** [comment]
i can share a repo but if you using any language you cant get a error.

**Comment by kkafar** [comment]
Hey @mehmettasan,

looking at the screenshot you provided, my first impression is that the problem might be  related to character encoding used by your language (notice that every `I` letter is replaced with some weird symbol)? To my best knowledge Turkish uses some diacritic signs that might not be encoded with ASCII (maybe even UTF-8) and different encoding could be problematic for compilers to handle? That is just my first guess and I must disclaim that my expertise is very limited in that matter 😅 However I'm not aware of anything special in any of those libs you mentioned (especially `react-native-screens`) that could lead to such problems. 

Is this problem of yours specific only to these libs? What happens if you try to build application that do not use them? Does the project compile then?

**Comment by mehmettasan** [comment]
> Hey @mehmettasan,
> 
> looking at the screenshot you provided, my first impression is that the problem might be related to character encoding used by your language (notice that every `I` letter is replaced with some weird symbol)? To my best knowledge Turkish uses some diacritic signs that might not be encoded with ASCII (maybe even UTF-8) and different encoding could be problematic for compilers to handle? That is just my first guess and I must disclaim that my expertise is very limited in that matter 😅 However I'm not aware of anything special in any of those libs you mentioned (especially `react-native-screens`) that could lead to such problems.
> 
> Is this problem of yours specific only to these libs? What happens if you try to build application that do not use them? Does the project compile then?

no, that's not the problem. It gets resolved when I change the kotlin version or change the system language to english. but when I install the package directly in Turkish language, it gives an error.

**Comment by kkafar** [comment]
Can you elaborate on what does installing package directly in Turkish mean? 

Do you change kotlin version of whole application or only "affected" libraries? 

To what version of Kotlin do you change?
If changing Kotlin version works for you it indicates that indeed compiler has some troubles with handling special characters / encoding.

Can you confirm for me, that building application without these libraries (`react-navigation`, `react-native-screens`, `react-native-safe-area-context`) works?

**Comment by mehmettasan** [comment]
https://github.com/th3rdwave/react-native-safe-area-context/issues/421

its my other issue for safe area context. i trying with clean project and just installing react navigation and this packages. i change kotlin version 1.9.0. you can look my other issue for more. some turkish people have this problem too.

**Comment by mehmettasan** [comment]
> Can you elaborate on what does installing package directly in Turkish mean?
> 
> Do you change kotlin version of whole application or only "affected" libraries?
> 
> To what version of Kotlin do you change? If changing Kotlin version works for you it indicates that indeed compiler has some troubles with handling special characters / encoding.
> 
> Can you confirm for me, that building application without these libraries (`react-navigation`, `react-native-screens`, `react-native-safe-area-context`) works?


https://github.com/th3rdwave/react-native-safe-area-context/issues/421

its my other issue for safe area context. i trying with clean project and just installing react navigation and this packages. i change kotlin version 1.9.0. you can look my other issue for more. some turkish people have this problem too.

**Comment by kkafar** [comment]
Hey, as this issue seems to be stale and all information I've managed to gather nudges me towards conclusion that this is rather a Kotlin compiler problem (as bumping it resolves the problem) I'll close the issue. 

I recommend setting custom kotlin version for now, however it is likely that in close future we will bump `kotlinVersion` used by this library.
