### ISSUE TITLE
 AAPT: error: attribute android:fromExtendBottom not found

### ISSUE THREAD

**Issue by mubashiralisiddiqui** [software-mansion/react-native-screens#1876]
### Description

getting error on android 

 ERROR:/Users/username/Desktop/Projects/React-native/project-name/node_modules/react-native-screens/android/build/intermediates/packaged_res/debug/anim-v33/rns_default_exit_in.xml:26: AAPT: error: attribute android:fromExtendRight not found.
getting this error after upgrading my React native version to the latest i.e. 0.72.4

"react-native-screens": "3.24.0"
 "react-native-router-flux": "^4.3.1"

### Steps to reproduce

1) Upgrade your react native version from react-native 0.70 to 0.72.4 (with the help of upgrade helper)
2). Run the application on Android 
you will get the error
<img width="895" alt="image" src="https://github.com/software-mansion/react-native-screens/assets/16689214/b2f53c68-4c28-4948-b6bf-23c49563681e">

### Snack or a link to a repository

link

### Screens version

3.24.0

### React Native version

0.72.4

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

Android emulator

### Device model

nexus 7

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hi @mubashiralisiddiqui
thanks for reporting, but this issue is missing a reproducible example, thus unless one is posted I'm going to close it. (Tag me, if reproduction is posted, I'll reopen and look into it).

I'm running application with 0.72.3/4 and `react-native-screens` from main on daily basis and it works fine -> issue arises *most likely* from some specific misconfiguration of your project.
The error message you provided indicates that `compileSkdVersion` / `targetSdkVersion` of your application is misconfigured (that should be located in `build.gradle` file and set to >= 33 to use these options).

**Comment by mubashiralisiddiqui** [comment]
@kkafar thanks for your response 
I am using compileSkdVersion  and target sdk version 33
and I am not using this library anywhere in my project its another library react-native-router-flux which is dependent on react-native-screens
I cannot provide my repo for security reasons but the error is clearly written if you can please look into the issue it will be a great help

**Comment by mubashiralisiddiqui** [comment]
I will create a new project and will try to reproduce it and will share the repo here

**Comment by glaydsoncosta** [comment]
Any news on this matter guys? I'm seeing the same bug and unable to build using targetSDK 33.
