### ISSUE TITLE
Long titles don't get truncated on native stack screens

### ISSUE THREAD

**Issue by thomasttvo** [software-mansion/react-native-screens#1946]
### Description

on iOS:
- When the `title` option is used on `ScreenStackHeaderConfig`, then the long title works great. ![image](https://github.com/software-mansion/react-native-screens/assets/2142140/979c7b2f-f2a3-434b-b0be-36100cf60343)

- However, when we use `ScreenStackHeaderCenterView`, the long title overlaps the right element. ![image](https://github.com/software-mansion/react-native-screens/assets/2142140/676db852-8e16-48c0-93e3-e426246838ae)

on Android:
- The long title overlaps the right element in both cases

### Steps to reproduce

mentioned in description

### Snack or a link to a repository

--

### Screens version

3.25.0

### React Native version

0.72.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @thomasttvo, thanks for submitting the issue!
Unfortunately this bug is not that easy to resolve - as for subviews of the header we're basically just using `Gravity` to position the elements, we're not calculating dynamically if the one subview will overlap another. Currently we've got planned something other to go around this bug, which is... to just `toolbar.isTitleCentered` for centerizing the title on Android (which already truncates the title) 😅 
This should fully fix this bug, as i believe centerizing the title for iOS is not necessary, since iOS already have the title centered?

More or less, I think centerizing the header's title will be much better than using center view for rendering header's title.

**Comment by thomasttvo** [comment]
> More or less, I think centerizing the header's title will be much better than using center view for rendering header's title.
do you mean that will fix Android in the case of using `title`? That's great if it works. We can switch to just using `title` if we need to.

Would still be great though for it to work with custom title views. Possibly some dynamic measurement might be the solution.

**Comment by hugo-advizr** [comment]
we're also facing this issue, any updates on this? thanks

**Comment by kkafar** [comment]
Yeah, I think I have some insight here now (on iOS).

Recently when working on [`UIBackButtonDisplayMode` support](https://github.com/software-mansion/react-native-screens/pull/2123) we've realised that this is OS behaviour when using anything custom in navigation item it disables certain native behaviours. Dunno what to do in this case yet, but it came to my mind that it might be worth trying out the new prop ☝🏻

**Comment by ApplyFrank** [comment]
still happening, I filed a bug in React Navigation, linking here since Github bot suggested I post in react-native-screens 
https://github.com/react-navigation/react-navigation/issues/12048

**Comment by kkafar** [comment]
Hey, I will update you here a bit, as we did spend some time debugging it. @alduzy please correct my message if I'm wrong at some point.

Talking Android here:

The text is properly truncated when it is mounted natively as `AppCompatTextView`. This happens when the title is passed as raw string (no component) and no `headerLeft` child is passed to header, because then we just pass the text to the Android API (`AppBar.title`) & it handles it.

In case when it is not properly truncated, so [when you specify `headerLeft` component or `headerTitle` is a component, not raw text we:](https://github.com/react-navigation/react-navigation/blob/229fd24314f94d61783db71c1b8ed05fcb75050e/packages/native-stack/src/views/HeaderConfig.tsx#L231)

1. render both components as children of `headerSubviewLeft`,
2. render title inside a react's text view.

What's important here: react's text view is laid out by Yoga. Yoga does use `flexShrink: 0` by default (in opposition to web, where `flexShrink: 1` is used) & we do not specify otherwise in `HeaderTitle` component. *If we set `flexShrink: 1` in `HeaderTitle` component **the text will be truncated correctly** unless `headerRight` is specified*. In such case, Yoga, for some yet unknown reason, does not respect `headerRight` component.

If you don't have `headerRight` you can workaround the issue by passing `headerTitle` as component and passing `flexShrink: 1` to the text component (container) you're using. 

## Possible solutions

Undecided yet.
