### ISSUE TITLE
TvOS crash with createNativeStackNavigator when I18nManager.forceRTL is set true

### ISSUE THREAD

**Issue by mehthabux** [software-mansion/react-native-screens#1948]
### Description

TvOS crash with createNativeStackNavigator when I18nManager.forceRTL is set true and never run until we make it false and build again

### Steps to reproduce

1. Create screens with createNativeStackNavigator
2. Add a button to switch to RTL mode -> I18nManager.forceRTL(true)
3. Restart the app

### Snack or a link to a repository

.

### Screens version

3.27.0

### React Native version

react-native-tvos@0.72.6-0

### Platforms

tvOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by tboba** [comment]
Hi @mehthabux, thanks for submitting the issue!

Our Github bot makes some valid points ☝🏻 . Marking it as stale and will close it shortly, unless proper reproduction is provided.

**Comment by prasad-r-g** [comment]
Hi @mehthabux did you get any solution for this ?

**Comment by karimhekal** [comment]
I faced the same issue, was only fixed by commenting
headerShown: false in screenOptions in the stack navigator 
Instead i used headerTransparent and headerTitle:''
If you try to hide the header by any means it will mostly crash, this was the only way to hide the header

<img width="277" height="137" alt="Image" src="https://github.com/user-attachments/assets/657d8312-938e-4a95-8bf4-e706676872d4" />
