### ISSUE TITLE
ios build failed

### ISSUE THREAD

**Issue by Shahrukh0396** [software-mansion/react-native-screens#2262]
### Description

Call to implicitly-deleted copy constructor of 'const facebook::react::ImageProps'

### Steps to reproduce

running app on ios simulator via xcode

### Snack or a link to a repository

https://bitbucket.org/lintontech/dreamroutes-app/src/main/

### Screens version

3.29.0

### React Native version

0.74.3

### Platforms

iOS

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @Shahrukh0396, thanks for reporting the issue. Please take a look into [compatibility table with Fabric in our readme](https://github.com/software-mansion/react-native-screens?tab=readme-ov-file#support-for-fabric).

Due to breaking changes in `react-native` packages, we can not keep backward compatibility on new architecture, also this is the reason why most recent `react-native` version is supported only by most recent `react-native-screens` version.

Please upgrade your `react-native-screens` version. If you will still encounter the error please file a new ticket **with working reproduction** (I can not access the repository you linked).
