### ISSUE TITLE
Incompatibility Issues with react-native-screens and Gradle Version

### ISSUE THREAD

**Issue by gesangseto** [software-mansion/react-native-screens#2422]
### Description

There are multiple errors encountered when trying to build the React Native project using the react-native-screens package. Below are the details of each error:

Error 1: Gradle Version Incompatibility
```
A problem occurred evaluating project ':react-native-screens'.
> Failed to apply plugin 'kotlin-android'.
  > The current Gradle version 6.7.1 is not compatible with the Kotlin Gradle plugin. Please use Gradle 6.8.3 or newer, or the previous version of the Kotlin plugin.
```
Steps attempted:
Upgraded Gradle wrapper to 6.8.3.
Error 2: MinCompileSdk Issue
```
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties) is greater than this module's compileSdkVersion (android-28).
      Dependency: androidx.appcompat:appcompat:1.4.2.
```
Steps attempted:
Updated compileSdkVersion to 31.
Error 3: Kotlin Compilation Errors
```
Task :react-native-screens:compileDebugKotlin FAILED
e: [file_path]: Unresolved reference: getSurfaceId
...
```

Expected Behavior: The project should compile and run successfully without any Gradle or Kotlin-related errors.

Environment:
```
React Native version: 0.63.4
react-native-screens version: 3.1.1
Gradle version: 6.7.1
Compile SDK version: 28
Operating System: Android
```

The project was previously running smoothly without any issues. However, without making any changes to the project, the errors suddenly started appearing. Notably, when I downgraded the react-native-screens version to 2.16.1, everything worked normally.

Any guidance on resolving these issues or recommended configurations would be appreciated.

Let me know if you need any more modifications!

### Steps to reproduce

1. Clone the repository.
2. Set up the project with react-native-screens and Gradle version 6.7.1.
3. Try building the project.

### Snack or a link to a repository

https://gitlab.com/mertrack/mertrack-v3_mobile_android_eisai

### Screens version

3.1.1

### React Native version

0.63.4

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Acknowledgements

Yes

**Comment by kkafar** [comment]
Hey @gesangseto, from information you provided I can see that you're using very very old version of `react-native-screens`. I guess you are limited by the `react-native` version you use in your project, however please note that we won't provide support for such "legacy" versions. I hope you understand that. 

I guess, the best way forward for you is to make use of `patch-package` and patch the version of react-native-screens manually. I can't conclude what is the root cause of the issue, but provided that nothing in the project changed and it "suddenly" stopped working, maybe you changed version of Android Studio or something? Something to try out: if you have more dependencies with native android code & they seem to be working fine & it is only `react-native-screens` which fails - try to copy `compileSdk` / `midCompileSdka` / `buildToolsVersion`, (most of the versioning in `build.gradle`) from other working lib and apply it to `react-native-screens`.

Also, if 2.16 works fine, checkout the diff between the versions, in particular one related to android building code - try to patch the changes.

**Note** it might be worth to try to clean all caches and run clean clean build. I've seen various errors as a result of outdated caches. `rm -fr node_modules android/build android/app/build android/app/.cxx`


I'll close issue but continue (as we won't work actively on a fix for such old version), but continue conversation.
