### ISSUE TITLE
[Feature Request] Implement gestureResponseDistance

### ISSUE THREAD

**Issue by harrisrobin** [software-mansion/react-native-screens#251]
Hello,

I was wondering if gestureResponseDistance is a feature that's planned to be implemented in this library. Currently, if you use native stack you lose `gestureResponseDistance` which is [implemented by stack navigator](https://github.com/react-navigation/stack/issues/309).

Cheers 🍻

**Comment by Jalson1982** [comment]
Is there any chance to implement this please?

**Comment by osdnk** [comment]
Hi, 
We'd like to ephazite that priority of React Native Screens is to deliver a native-like experience with a minimal cost of modifying what's actually delivered by the Platform. 
Therefore we don't want to go for supporting features that are not ready out of the box or easy to implement by native components' kit.
Feel free to make this change in your fork or patch but I need to want you that messing with UIKit is what you most likely don't want to do 😃

**Comment by WoLewicki** [comment]
I am closing this issue. Feel free to comment if you have any questions.

**Comment by tgensol** [comment]
Do you think that feature can be implemented ? 

If you see an iOS user, they will all struggle to move back as every others native applications put a gestureDistance bigger (instagram, facebook, snapchat,...).... 

I stopped using your lib and went back to **@react-navigation/stack** because the main issue we had from users was that difficulty for going back in our app (and we asked thousands of people). 

Or do you have any idea how to change it in your lib ? 

Thanks !

**Comment by WoLewicki** [comment]
@tgensol I am afraid there is no such option, as @osdnk mentioned. Although if you manage to find even a hacky solution to this, we are always open for PRs.

**Comment by JackShannon** [comment]
@WoLewicki 

https://github.com/fastred/SloppySwiper

Would it be possible to use this library?
