### ISSUE TITLE
Modal blinking on different screens with previous content

### ISSUE THREAD

**Issue by denysoleksiienko** [software-mansion/react-native-screens#2544]
### Description

I created a simple dropdown menu using a native modal, but for some reason after closing it, the content of the previous modal appears in a blinking on the next screen where the dropdown menu using another content 

https://github.com/user-attachments/assets/ce7c986c-ebfe-4627-835b-f9a6dcf54a19

### Steps to reproduce

* run ``yarn``
* run ``yarn pod-install``
* run ``yarn start``
* run ``yarn ios``
* open menu on home screen
* open menu on profile screen
* you will see the blinking previous modal

### Snack or a link to a repository

https://github.com/denysoleksiienko/react-native-modal-blinking

### Screens version

^4.3.0

### React Native version

0.76.3

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by denysoleksiienko** [comment]
resolved by adding:
```
if (!visible && position) {
  return null;
}
```

**Comment by TonyFTannous-Byd** [comment]
same issue for me. but why before this version 4.0.0 we dont need to set this condition
it be enough to do that:
if (visible) {
   <Modal ..../>
 }

**Comment by Jpoliachik** [comment]
I'm still experiencing this too
"react-native": "0.76.7",
"react-native-screens": "4.4.0",

this issue should be reopened IMO

**Comment by fbeaulieu** [comment]
I got the same issue using react-native 0.76.6 (on Ios) and I finally figured out a way out of it. Apparently, React Native modal keeps itself "alive" in some way (well it's a modal/portal kind of) and if seems to "retain" its previous content which displays "in between" the visibility transition.

In cause it can help anyone, I just put together a simple OverlayContainer (which uses Modal), but that clear it's content prior to "close" itself, so next time it reopen, there is just NO previous content.

(note my version also displays a Pressable container which is behind the content to be displayed for me to be able to close the modal whenever user press outside of the "Content" view.

`import { Modal, Pressable, View } from 'react-native';
import React, { useEffect } from 'react';

export interface IOverlayContainerProps {
  children: React.ReactNode;
  visible: boolean;
  onPressOutsideContent?: () => void;
}

export const OverlayContainer = ({ children, visible, onPressOutsideContent }: IOverlayContainerProps) => {
  const [modalVisible, setModalVisible] = React.useState(visible);
  const [contentVisible, setContentVisible] = React.useState(visible);

  // This "patch" is a workaround to the RN Modal issue
  // where it flashes the previous content upon closing.
  // This trick is that whenever the Modal is set to VISIBLE FALSE,
  // it must first hide its content to flush it from Modal internal
  // memory, and then close the Modal itself, so the next time it 
  // become visible again, it will not show the any previous content
  // since it's been flushed the last time it was closed. It's kind
  // of a 2-step "make it invisible" process...
  useEffect(() => {
    // Closed by the parent...
    if (!visible) {
      setContentVisible(false);
    }
    else {
      setModalVisible(true);
      setContentVisible(true);
    }
  }, [visible]);

  // Since content visibility is controlled by THIS container,
  // we need to explicitly close the modal when the content is hidden.
  useEffect(() => {
    // Closed by the parent...
    if (!contentVisible && !visible) {
      setModalVisible(false);
    }
  }, [contentVisible]);

  return (
    <Modal transparent={true} visible={modalVisible} onRequestClose={onPressOutsideContent}>
      {contentVisible && (
        // PICKER FULLSCREEN CONTAINER VIEW
        <View
          style={{
            height: '100%',
            width: '100%',
            zIndex: 98,
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          {/* OVERLAY CONTENT */}
          {children}

          {/* PRESS OUTSIDE HANDLER */}
          <Pressable
            style={{
              position: 'absolute',
              height: '100%',
              width: '100%',
              backgroundColor: 'black',
              opacity: 0.2,
              zIndex: 95, // Meant to be lower than the content's
              borderRadius: 5,
              borderWidth: 0.25,
              borderColor: 'gray',
              justifyContent: 'center',
              alignItems: 'center',
            }}
            onPress={() => {
              onPressOutsideContent?.();
            }}
          />
        </View>
      )}
    </Modal>
  )
};`

**Comment by joshua-revolutions** [comment]
I have this bug when new architecture is enabled. Tested on IPadOS. Turning off new arch fixes the issue.

**Comment by lsapozh** [comment]
@denysoleksiienko this issue is still happening, can we re-open it?

**Comment by rahul-durgam** [comment]
yes i'm still facing same issue in iOS -> react-native:"0.78.1"

**Comment by szymonWCa** [comment]
Same issue react-native:"0.79.5", react-native-screens:"4.11.1"

> [@Jpoliachik](https://github.com/Jpoliachik)
> 
> I got the same issue using react-native 0.76.6 (on Ios) and I finally figured out a way out of it. Apparently, React Native modal keeps itself "alive" in some way (well it's a modal/portal kind of) and if seems to "retain" its previous content which displays "in between" the visibility transition.
> 
> In case it can help anyone, I just put together a simple OverlayContainer (which uses Modal), that clear it's content prior to "close" itself, so next time it reopen, there is just NO previous content.
> 
> (note my version also displays a Pressable container which is behind the content to be displayed for me to be able to close the modal whenever user press outside of the "Content" view.
> 
> **OverlayContainer.tsx**
> 
> ```
> import { Modal, Pressable, View } from 'react-native';
> import React, { useEffect } from 'react';
> 
> export interface IOverlayContainerProps {
>   children: React.ReactNode;
>   visible: boolean;
>   onPressOutsideContent?: () => void;
> }
> 
> export const OverlayContainer = ({ children, visible, onPressOutsideContent }: IOverlayContainerProps) => {
>   const [modalVisible, setModalVisible] = React.useState(visible);
>   const [contentVisible, setContentVisible] = React.useState(visible);
> 
>   // This "patch" is a workaround to the RN Modal issue
>   // where it flashes the previous content upon closing.
>   // The trick is that whenever the Modal is set to VISIBLE FALSE,
>   // it must first hide its content to flush it from Modal internal
>   // memory, and then close the Modal itself, so the next time it 
>   // become visible, it will not show any previous content
>   // since it's been flushed the last time it was closed. It's kind
>   // of a 2-step "make it invisible" process...
>   useEffect(() => {
>     // Closed by the parent...
>     if (!visible) {
>       setContentVisible(false);
>     }
>     else {
>       setModalVisible(true);
>       setContentVisible(true);
>     }
>   }, [visible]);
> 
>   // Since content visibility is controlled by THIS container,
>   // we need to explicitly close the modal when the content is hidden.
>   useEffect(() => {
>     // Closed by the parent...
>     if (!contentVisible && !visible) {
>       setModalVisible(false);
>     }
>   }, [contentVisible]);
> 
>   return (
>     <Modal transparent={true} visible={modalVisible} onRequestClose={onPressOutsideContent}>
>       {contentVisible && (
>         // FULLSCREEN CONTAINER VIEW WITH SCREEN CENTER {children}
>         <View
>           style={{
>             height: '100%',
>             width: '100%',
>             zIndex: 98,
>             justifyContent: 'center',
>             alignItems: 'center',
>           }}
>         >
>           {/* OVERLAY CONTENT */}
>           {children}
> 
>           {/* PRESS OUTSIDE HANDLER */}
>           <Pressable
>             style={{
>               position: 'absolute',
>               height: '100%',
>               width: '100%',
>               backgroundColor: 'black',
>               opacity: 0.2,
>               zIndex: 95, // Meant to be lower than the content's
>               borderRadius: 5,
>               borderWidth: 0.25,
>               borderColor: 'gray',
>               justifyContent: 'center',
>               alignItems: 'center',
>             }}
>             onPress={() => {
>               onPressOutsideContent?.();
>             }}
>           />
>         </View>
>       )}
>     </Modal>
>   )
> };
> ```

This not helping

**Comment by kkafar** [comment]
Okay, why do you think this issue is related to `react-native-screens`? I see `Modal` component from `react-native` misbehaving here.

**Comment by mellokayy** [comment]
> Okay, why do you think this issue is related to `react-native-screens`? I see `Modal` component from `react-native` misbehaving here.

Other users report the same info, so I put the versions I'm using too...

**Comment by mellokayy** [comment]
The problem is happening because of `animationType="fade"`, I was able to reproduce it in a more simplified way here: https://github.com/mellokayy/modal-blinking and https://github.com/mellokayy/modal-blinking-expo-53

At Expo 54, this problem happens differently, the modal itself blinking instead of the previously opened modal. One way to "fix" it is to change the animation to "none".

**Comment by dhavdc** [comment]
I had this problem when I was trying to render a Modal inside another Modal. Getting rid of the nesting fixed it for me. At least for now it seems like

**Comment by jamespageced** [comment]
This was happening in the dropdown library we were using for only IOS. At first I thought it was the dropdown, and so I tried many other dropdown libraries (all with their own issues with IOS). Eventually I created my own and used a modal with a flatlist instead of a dropdown. Now we are seeing the modal flicker (which led me here). The issue is one of our Stack.Screen `options={{ headerShown: false, presentation: 'transparentModal' }}`. When clicking the back button on the Stack.Screen modal, it goes to the previous screen causing the dropdown(or modal) on that previous screen to flash for a second. We've spent weeks figuring out the issue was the Stack.Screen modal and not the dropdown library itself. Now I have to rewrite much of the code to see if I can get the header icon to have it's own modal instead of treating it like it's own screen(s). Expo sdk53 has been a serious thorn in our side.
