### ISSUE TITLE
In Jest environment, header of native-stack modal is rendered twice

### ISSUE THREAD

**Issue by thomasttvo** [software-mansion/react-native-screens#2569]
### Description

In `NativeStackView.native.tsx`, the `SceneView` renders both the header and `MaybeNestedStack`, and then `MaybeNestedStack` checks if it's a modal, then renders the header again inside. This might be ok in real-life because we're resolving these header configs in the native world, but in Jest they just got rendered as regular components and can be duplicated.

### Steps to reproduce

Open a modal route in jest, then check the tree. 

### Snack or a link to a repository

-

### Screens version

3.34.0

### React Native version

0.73.5

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Acknowledgements

Yes

**Comment by kkafar** [comment]
@thomasttvo thanks for reporting. What would be the expected behaviour in your opinion? And could you describe what problem it leads to?  My initial impression is that we won't want to change anything here, because we would have to manipulate the view hierarchy only for test purposes - what I'm not sure makes much sense. The "duplicated header element" you get in tests is what is actually rendered in React Element Tree in production also

**Comment by thomasttvo** [comment]
@kkafar this is adding friction and confusion to writing jest tests because if we're looking for a particular test-ID, jest would unexpectedly throw an error saying there are 2 test-IDs. You would think we can just use `queryBy` to get an array of components and pick the first one, but then the test becomes flaky if you start having more of such components on the screen. The fix to me is as easy as checking if `jest` is defined, and if it is, don't render one of the two elements.
