### ISSUE TITLE
Collapsible header / modal swipe gesture on inverted ScrollView

### ISSUE THREAD

**Issue by Hirbod** [software-mansion/react-native-screens#263]
If you have a ScrollView with inverted property, the LargeTitleHeader behaves accordingly. 

If the ScrollView is set to inverted (often the case with chats where messages appear at the bottom) and the whole thing takes place in a modal, you have to swipe backwards to close the modal. This is not an error in itself, but there should be the possibility or a prop for these cases to explicitly reverse the behavior.

**Comment by WoLewicki** [comment]
Can you create a repo with the minimal configuration that shows the issue?

**Comment by Hirbod** [comment]
Just open a modal in native-stack with a <FlatList inverted={true}> and try to close the modal by swiping down. It wont work, since the direction is reversed. So I need to slide up to move the modal down.

(The FlatList ofc needs to have a height bigger then the viewport)

**Comment by Hirbod** [comment]
@WoLewicki this is how facebook fixed it for the status bar tab:
https://github.com/facebook/react-native/commit/7a4753d76aab1c52a09f26ec6f7fd43a68da8a97

it would be nice if you guys could also implement in the same fashion so a modal, which contains a inverted Scrollview or FlastList, works as expected (and not reversedd)

**Comment by berkaey** [comment]
Yes, this is a real issue for chat views inside modals on iOS 13. Any suggested workarounds for this type of use case. Do we even stop propagation between nested scroll views?

**Comment by berkaey** [comment]
@Hirbod did you find any solution?

**Comment by Hirbod** [comment]
There is no solution currently @berkaey. react-native-screens needs to fix this. I would love to help but my obj-c/ios native development skills are super limited. I think the listener values for the swipe down gesture have to be reversed (or listen for negative)

**Comment by berkaey** [comment]
Can we implement something similar to this https://stackoverflow.com/a/59462475? @WoLewicki Otherwise, we and probably many more can't use native modal patterns in a chat app or something similar. We need a programmatic control of the gesture recognizers somehow.

**Comment by WoLewicki** [comment]
It might not be possible to change the direction of dragging to dismiss a modal from the native side. If you find an example where it is done on the native side, please share an example.
About disabling the gesture on the modal and the thread from SO you sent @berkaey, you can use RNGH to catch the gesture events. You can look at the gist:  https://gist.github.com/WoLewicki/7a6f5ceebc228ad5ac8aaeb7bd5a6a36 where the box takes over the gestures and stops the screen from dismissing.

**Comment by Hirbod** [comment]
This could be the solution:

https://github.com/gorhom/react-navigation-scrollable-modal

**Comment by WoLewicki** [comment]
I think this component is to be used strictly in `stack` navigator with its `PanGestureHandler` while the native iOS modal from `native-stack` uses the native behavior under the hood. But it for sure is worth trying.

**Comment by Hirbod** [comment]
I just thought that the provided patch with RNGH might intercept and prevent the native gestures but I did not try it yet due to limited time

**Comment by WoLewicki** [comment]
I will close this issue since, as mentioned in the previous comments, we have no control over the mechanism of dismissing the modal when the scrollView is used. The current behavior is an effect of what `react-native` does under the hood, being this: https://github.com/facebook/react-native/blob/a0c3c85879ece499ea7355f736187bed2ccfec23/Libraries/Lists/VirtualizedList.js#L2122. It makes the bottom of the scrollView its beginning, so scrolling further down is interpreted similarly as scrolling up in the non-inverted case. One solution I can think of is doing something similar to what e.g. Messenger app does, which is rendering kind of `ActivityIndicator` which will take over the gesture (you can see same thing here: https://github.com/software-mansion/react-native-screens/issues/640). Feel free to comment here if something is wrong.
