### ISSUE TITLE
@react-navigation/stack on ios?

### ISSUE THREAD

**Issue by compojoom** [software-mansion/react-native-screens#312]
We are doing some e2e tests with detox. We often had the problem that we do by.id("something") and detox would say - several elements match identifier. 

Turning react-native-screens on solved this issue on Android since the screens behind the active one are not rendered. I noticed however that this is not the case on iOS. When I inspect the app in XCode I can see that scenes that shouldn't be visible are rendered. 

I checked the Example in this repo and there the screens that are behind the active one are not rendered. it turns out that there we have:
```
import createNativeStackNavigator from 'react-native-screens/createNativeStackNavigator';
```

So my question is - do I need to use createNativeStackNavigator if I  want the Screens not to render behind the active one? The docs say that the only thing we need to do is to call enableScreen, but this doesn't seem to do anything with @react-navigation/stack v2?

**Comment by WoLewicki** [comment]
`react-native-screens` are not enabled in `@react-navigation/stack`, which you can see here: https://github.com/react-navigation/react-navigation/blob/master/packages/stack/src/views/Stack/CardStack.tsx#L384. It is disabled due to some bugs happening when wrapping navigation with `RNScreens`. Does it solve your issue?

**Comment by compojoom** [comment]
Ok, now at least I know what's going on. Thanks for the information @WoLewicki !
