### ISSUE TITLE
[native-stack] Can't navigate to nested native stack navigator from native stack navigator

### ISSUE THREAD

**Issue by satya164** [software-mansion/react-native-screens#368]
_Moved from [react-navigation/react-navigation#6761](https://github.com/react-navigation/react-navigation/issues/6761). Originally opened by @foonx_
___

**Current Behavior**

I Currently have

- Main native stack navigator
  - Main menu screen (this is the initial route)
  - Nested native stack navigator
    - List Screen

**Expected Behavior**

I want to navigate from the main menu screen to the nested stack navigator. It works when using normal stack navigators.

**How to reproduce**

I created a [snack](https://snack.expo.io/@metec_roger/nested-navigator-problem) to reproduce the problem.
Currently it doesn't work, trying to navigate from the homescreen to the profile screen doesn't work. But if you change initial route from 'Home' to 'SubStack' on line 52, then it is possible to navigate from the sub stack to home screen and back.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |  Android 9
| @react-navigation/native       |  next
| @react-navigation/native-stack |  next
| react-native-screens           |  2.0.0-alpha.12
| react-native                   |  
| expo                           |  36
| node                           |  v10.16.2
| npm or yarn                    |  npm 6.13.6

**Comment by WoLewicki** [comment]
@foonx according to the snack it does not work for native-stack and normal stack. You can also not use the `enableScreens()` and you will see the same. It is like that due to the fact that the second screen is not rendered. The second screen in the main navigator is also a navigator, and if it is not rendered, the `Profile` screen does not exist because the nested navigator does not exist. (the second screen is null). I am closing it. Feel free to comment if I am wrong or you have any other questions.
