### ISSUE TITLE
View controller based status bars

### ISSUE THREAD

**Issue by jacobp100** [software-mansion/react-native-screens#495]
It would be neat if we could set the status bar style on a screen. It would mean fewer issues from imperative status bar handling people tend to have to do in the app. I know on iOS this can be done via view controller based status bars - not sure about Android

**Comment by WoLewicki** [comment]
Would you like to make a PR with this functionality?

**Comment by jacobp100** [comment]
I can take a shot at it!

**Comment by WoLewicki** [comment]
Great!

**Comment by jacobp100** [comment]
I made a start over here - https://github.com/jacobp100/react-native-screens/tree/status-bar-styles

I can't figure out how to get it to register the correct view controller as the status bar controller. Do you have any ideas?

**Comment by WoLewicki** [comment]
In order to activate this in `native-stack`, you also have to apply similar changes as in `AppDelegate.m`, but in `RNSScreenStack.m`: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStack.m#L38. This should also respond to `childViewControllerForStatusBarStyle`. I made a PR that applies this change: https://github.com/software-mansion/react-native-screens/pull/642, but it seems not to be working for all cases, like going to the `nativeNavigation.js` for the first time, `AppDelegate's` `childViewControllerForStatusBarStyle` is not called for some reason. Can you elaborate on this?

**Comment by WoLewicki** [comment]
Also, this cannot be used alongside with RN `StatusBar` component and there is no option to hide the status bar in your changes. Were you going to work on it also? Otherwise, there is no need for the `statusBarAnimation` prop.

**Comment by WoLewicki** [comment]
I updated the PR so it should work with nested `native-stacks` and get the options from the deepest one. It should also now work with `native-stack` nested in other navigators that use `ScreenContainer`.
