### ISSUE TITLE
While go back to screen with large title, position of content is jumping

### ISSUE THREAD

**Issue by ArekChr** [software-mansion/react-native-screens#504]
Content of screens jumps, like top padding/margin changes while view is focused.

This issue is very weird because it occur only when I have title with special Polish characters,
Tested on title with Polish characters: "Szczegóły" and without "Szczegoly". in second one there is no issue.

When screen with Polish characters is opened first time then this issue occurs in every screen while going back to screen with large title.

code: 

```
const NativeStack = createNativeStackNavigator();

function First({ navigation }) {
    return (
        <ScrollView style={{ backgroundColor: 'pink', flex: 1 }}>
            <Button title='Go To Second' onPress={() => navigation.navigate('Second')} />
        </ScrollView>
    );
}

function Second({ navigation }) {
    return (
        <ScrollView style={{ backgroundColor: 'yellow', flex: 1 }}>
            <Button title='Go To First' onPress={() => navigation.goBack()} />
        </ScrollView>
    );
}

export function BugStack() {
    return (
        <NativeStack.Navigator>
            <NativeStack.Screen name='First' component={First} options={{ headerLargeTitle: true }} />
            <NativeStack.Screen name='Second' component={Second} options={{ title: 'Szczegoly' }} />
        </NativeStack.Navigator>
    );
}
```

![bug](https://user-images.githubusercontent.com/24796318/81443133-1e133d80-9175-11ea-9eb9-95e9ef13c24b.gif)
![ok](https://user-images.githubusercontent.com/24796318/81443144-22d7f180-9175-11ea-9abc-227be50b23d3.gif)

```
- @react-navigation/native: 5.2.6
- @react-navigation/stack: 5.3.1
- react-native-screens: 2.7.0

platform: iOS
mode: Debug and Release (issue on both)
Device: iPhone XS
OS version: 13.4.1
```

**Comment by LukaszBisewski** [comment]
Same issue.

**Comment by WoLewicki** [comment]
The bug seems to come from the native problems with a large title's UILabel frame. If you debug it in Xcode, you can see that the special characters make the UILabel have 8,5 points more in height's value, which is then applied to the whole header height but is not applied to the screen below it. You can spot it easier by setting large titles on both screens and setting special characters in the second one. It will have the wrong alignment when you navigate to it for the first time. I did not find a workaround for it yet.

**Comment by ArekChr** [comment]
So as far as I know this error will also occur in the same setup in pure Objective-C or Swift?

**Comment by WoLewicki** [comment]
Yeah, from what I got, the UILabel of the header's title changes there too. But the handling of the error there can be different so the bug will not be so easy to spot.

**Comment by WoLewicki** [comment]
I looked at it again and it seems that breaking the constraints of the UILabel height in the large title is fixed by changing the header to be small on the previous screen. It is required to have `headerTranslucent` set to `true` and `ScrollView` with `contentInsetAdjustmentBehavior="automatic"` as a root view of the screen (they are recommended options with large header anyway). You can see it on the attached GIF. I think there is nothing else that can be done since it is native behavior, but I might be wrong. I am closing this issue then. Feel free to comment if you have any questions.
![gif](https://user-images.githubusercontent.com/32481228/90769891-41f82a80-e2f1-11ea-979a-382305a3a9d0.gif)
