### ISSUE TITLE
large title is never translucent when backgroundColor is set

### ISSUE THREAD

**Issue by kyle-ssg** [software-mansion/react-native-screens#524]
**Works fine when backgroundColor is transparent**
```
        largeTitleBackgroundColor:"transparent",
        largeTitleHideShadow:true,
        backgroundColor:"transparent",
        translucent:true
```

![image](https://user-images.githubusercontent.com/8608314/82735081-0ca26780-9d17-11ea-8b8c-50c8864eed52.png)

**Causes large title to be opaque**
```
    largeTitle:true,
    largeTitleBackgroundColor:"transparent",
    backgroundColor:"white",
    backTitle:"Back",
    translucent:true
```
![image](https://user-images.githubusercontent.com/8608314/82735088-1af08380-9d17-11ea-9cf3-80fe8299ebc5.png)

**Comment by WoLewicki** [comment]
Can you provide a snack that shows it? I think it is the matter of the implementation, which you can check here: https://github.com/software-mansion/react-native-screens/blob/master/ios/RNSScreenStackHeaderConfig.m#L261

**Comment by kyle-ssg** [comment]
@WoLewicki 
https://snack.expo.io/@kyle-ssg/large-title-is-never-translucent-when-backgroundcolor-is-set

Here I wish the large title to be transparent and the small title (when scrolled up) to be white.

**Comment by WoLewicki** [comment]
I am afraid that the thing you are trying to achieve is impossible since the "small" title is always rendered behind the "large" title, but it is not visible due to the color of "large" title. You can see it on this image:
![image](https://user-images.githubusercontent.com/32481228/85745179-ca998680-b705-11ea-9131-ade414e3f1ec.png)
So while setting the "large" title's color to transparent, the "small" title's color is visible, causing the half of the "large" header being transparent and another half to be white.
![image](https://user-images.githubusercontent.com/32481228/85745624-2237f200-b706-11ea-9c9f-fe562d32387b.png)

**Comment by kyle-ssg** [comment]
Right, ok. But if I try anything that isn't transparent I get a visual glitch as shown here 
<img src="https://recordit.co/ZVLB8YJLC0.gif"/>

**Comment by WoLewicki** [comment]
```
import {NavigationContainer} from '@react-navigation/native';
import React from 'react';
import {ScrollView, View, Button} from 'react-native';
import {createNativeStackNavigator} from 'react-native-screens/native-stack';
import {enableScreens} from 'react-native-screens';
enableScreens();

const Stack = createNativeStackNavigator();

export default function NativeNavigation() {
  return (
    <NavigationContainer>
      <Stack.Navigator
        screenOptions={{
          headerTranslucent: true,
        }}>
        <Stack.Screen
          name="Status"
          component={Status}
          options={({navigation}) => ({
            headerLargeTitle: true,
            headerLeft: () => (
              <Button
                title="Privacy"
                onPress={() => navigation.navigate('Privacy')}
              />
            ),
            headerLargeStyle: {
              backgroundColor: 'red',
            },
            headerStyle: {backgroundColor: 'yellow'},
          })}
        />
        <Stack.Screen
          name="Privacy"
          component={Privacy}
          options={{headerStyle: {backgroundColor: 'yellow'}}}
        />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

function Status() {
  return <ScrollView />;
}

function Privacy() {
  return <View />;
}
```

What is wrong with e.g. this code? It replicates how the transition in WhatsApp works but with additional header colors that you need if I am correct.

**Comment by kyle-ssg** [comment]
Hey @WoLewicki, thanks for being patient with this. So the above is the closest I got, however there are indeed 2 things wrong with this. The following is a frame from popping from Privacy to Status

Desired outcome:
![image](https://user-images.githubusercontent.com/8608314/85884833-271aa580-b7db-11ea-8240-0f05b9f7e007.png)

Current Result:
![image](https://user-images.githubusercontent.com/8608314/85884756-0baf9a80-b7db-11ea-9613-ab1831c7dbd9.png)

1: The NavBar from the status screen overlays the privacy screen
2: The visual glitch which I think is actually part of the issue mentioned here https://github.com/software-mansion/react-native-screens/issues/520#issuecomment-648850872

**Comment by WoLewicki** [comment]
I am not sure if I understand correctly what do you mean, but I think the transition used in WhatsApp is not a default large-small header transition because the small header going out of the screen like that is the default transition of small-small header. The one from my comment feels the same as the transition of the large-small header in Messages App where the small header is becoming bigger and losing the bottom shadow and the previous items are fading out and the current are fading in. I think it is impossible to implement the behavior you would like without implementing a custom transition for the header. You can also see that in WhatsApp the header in the Status screen becomes small by itself after 2 transitions between it and Privacy screen, which seem to be due to the modification of default behavior. Correct me if I am wrong, please.

**Comment by kyle-ssg** [comment]
@WoLewicki I see, yeah I guess there is a possibility that their implementation is totally custom, though the more I look at it I'm not so sure, the transition in WhatsApp if I'm not mistaken is the same as the transition that's in the standard iOS settings screen from what I can see, I'd find it a bit surprising if this weren't replicable. 

<img src="http://g.recordit.co/zpbUfnGjMc.gif"/>


I've managed to get a bit closer, it seems adding largeHeader settings to the privacy screen helps even though it doesn't display a large title.

<img src="http://g.recordit.co/e76ErxvoRs.gif"/>


However it's still not quite right, to me it just seems like the issue is that the privacy screen navbar is on top of the navbar it's popping to (the status screen).

**Comment by WoLewicki** [comment]
I cannot think of the modification of native code that would change this "fade-in fade-out" transition to the "slide out" one. If you would find a native iOS project where it is implemented, I could maybe work with it somehow. In a simple Swift project with the same configuration, the transition is the same as in `react-native-screens`.

**Comment by kyle-ssg** [comment]
Sure ok @WoLewicki I'll see if I can find something

**Comment by kyle-ssg** [comment]
@WoLewicki you're totally right about this, playing around with Navigation Controllers no matter what I try it behaves like this. How strange, I wonder what they are doing differently.

**Comment by WoLewicki** [comment]
They probably implemented custom transitions for this.
