### ISSUE TITLE
Navigation Conflicts with React Native Modal Component

### ISSUE THREAD

**Issue by jacobp100** [software-mansion/react-native-screens#529]
If I render a `<Modal />` component from `react-native` within a native stack and navigate while dismissing the modal, it either freezes with the modal open, freezes with the modal shut, or closes the modal, reopens the modal, then freezes. Generally, it freezes.

We mostly use `react-navigation`, but I also think there are good uses for the modal component. We have a case where we have a modal that asks the user if they want push notifications when they've met some criteria. They can press no, and then meet the criteria again at a later date. Doing this with the `Modal` component is much more ergonomic here because of the `visible` prop. We don't have to do imperative navigation to handle this.

It's not entirely clear whether this is a bug here - maybe it's up to `react-navigation` to render a modal within a stack, and then have a mechanism for conditionally displaying that. Or maybe is is a bug here, and we need better handling with modals that are not our own. I know I have apps that show iOS modals for stuff like the file picker. What are your thoughts here?

I've made a reproduction over here https://github.com/jacobp100/react-native-screens/tree/react-native-modal-example ([diff](https://github.com/software-mansion/react-native-screens/compare/master...jacobp100:react-native-modal-example))

**Comment by r0b0t3d** [comment]
Your problem could be related to this https://github.com/facebook/react-native/issues/26892
On ios 13, modal will be displayed as `pagesheet` by default. But when swiping down to dismiss, it doesn't trigger the callback to let us reset the state of modal.

**Comment by WoLewicki** [comment]
It might mess with `react-native-screens` since we operate on modal views in our code and the modal from the <Modal /> component is also one of those: https://github.com/facebook/react-native/blob/d0871d0a9a373e1d3ac35da46c85c0d0e793116d/React/Views/RCTModalHostViewManager.m#L21. I am not sure what is the root of the problem, but I would suggest using modal presentation style of native-stack for such things. There should not be too much configuration needed to be able to show a modal screen anywhere in the app, just add another navigator at the top of the project with the first screen containing all of the application, and another being the modal you want to display.

**Comment by WoLewicki** [comment]
Is there anything more I can help you with regarding this issue? Or can I close it?

**Comment by jacobp100** [comment]
Sorry, I got nowhere fixing this issue, and I no longer work at the company that was having the issue. I do remember reaching the same conclusion as you for the cause - I just wasn't able to fix it. I think it's a nice to have if it can be supported though.

**Comment by tedi** [comment]
I'm also experiencing the same issue. I ended up creating a new flow for my use case, but I also experienced the same thing when calling React Native Modal on load from a Modal screen.

**Comment by WoLewicki** [comment]
Closing this in order to keep the discussion in one place (#525).
