### ISSUE TITLE
[Question] How do I make a half-opened Modal/ActionSheet?

### ISSUE THREAD

**Issue by mrousavy** [software-mansion/react-native-screens#530]
How do I make a 2 stage Action Sheet/Form Sheet like the iOS Share Sheet?

<table>
<tr>
<th>Closed</th>
<th>Partially opened</th>
<th>Fully opened</th>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/15199031/83522193-9e149500-a4e0-11ea-9a9b-f31533ded6fe.png"/> </td>
<td><img src="https://user-images.githubusercontent.com/15199031/83522233-abca1a80-a4e0-11ea-92bd-6cc117d2ea7f.png"/> </td>
<td><img src="https://user-images.githubusercontent.com/15199031/83522237-ae2c7480-a4e0-11ea-851a-dc938b31e25f.png"/> </td>
</tr>
</table>

**Comment by Hirbod** [comment]
@mrousavy maybe you wanna use something like this for it
https://github.com/jeremybarbet/react-native-modalize

It has everything you need. And there is also an example how you can shrink the view behind it using the animatedpangesture value

**Comment by WoLewicki** [comment]
It is currently not possible with `react-native-screens`.

**Comment by WoLewicki** [comment]
Actually, one way to do this is to set `stackPresentation: 'transparentModal'` and properly arrange the views in it. Since the content below will be still visible and the modal takes the whole screen, you can display such things there and even nest a stack in it, if it is needed. `react-native` modal use such native presentation style when applying `transparent` option too. I will close this issue then. Feel free to comment if you need more information. You can also check #525.

**Comment by Gregoirevda** [comment]
@WoLewicki Is there a way to integrate [adaptiveSheetPresentationController](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller/3810055-adaptivesheetpresentationcontrol?changes=__4) in the repo?

**Comment by Gregoirevda** [comment]
Ok, noticed this is ongoing in PR #1649
