### ISSUE TITLE
error: Error: Unable to resolve module `react-navigation-stack`

### ISSUE THREAD

**Issue by luatnd** [software-mansion/react-native-screens#621]
> Error: Unable to resolve module `react-navigation-stack` from `node_modules/react-native-screens/src/createNativeStackNavigator.js

With react-navigation@5.x they use `@react-navigation/stack` instead of `react-navigation-stack`

**Comment by WoLewicki** [comment]
What is the purpose of this issue? Can I help you with something?

**Comment by WoLewicki** [comment]
I think the error you got is due to the usage of not the proper navigator. You should do it like that: https://github.com/software-mansion/react-native-screens/tree/master/native-stack#api-definition `import { createNativeStackNavigator } from 'react-native-screens/native-stack';` for react-navigation v5. I am closing this issue then. Feel free to comment if it is not what you meant.

**Comment by luatnd** [comment]
Yes,
I mean https://github.com/software-mansion/react-native-screens/blob/94bb918376200899f4c09e7935f573937c000010/src/createNativeStackNavigator.js#L18 is still importing `react-navigation-stack` 
Should you increase a version to support react-navigation@5.x?

**Comment by WoLewicki** [comment]
Because it uses the previous version of `react-navigation`. There are 2 version that can be used. One you mentioned in `react-native-screens/src/createNativeStackNavigator.js` (for older version) and one in `react-native-screens/src/native-stack/navigators/createNativeStackNavigator.tsx`

**Comment by luatnd** [comment]
That's a clear answer, thanks.
I haven't notice that it was mentioned here:
https://github.com/software-mansion/react-native-screens#using-createnativestacknavigator-with-react-navigation
