### ISSUE TITLE
Large header hides on back from screen with default header

### ISSUE THREAD

**Issue by ArekChr** [software-mansion/react-native-screens#627]
![ezgif-7-357e3b3a8104](https://user-images.githubusercontent.com/24796318/92598213-c9a9d700-f2a8-11ea-9df0-9d9cccb69107.gif)

iPhone 11 (13.4)

"react-native": "0.62.2"
"@react-navigation/bottom-tabs": "^5.8.0"
"@react-navigation/native": "^5.7.3"
 "@react-navigation/stack": "^5.9.0"

**Comment by ArekChr** [comment]
This issue occur also in your gif here https://github.com/software-mansion/react-native-screens/issues/504#issuecomment-677634943
When you go back from third screen to second

**Comment by WoLewicki** [comment]
I am afraid it is a native behavior and you can spot it e.g. in Settings on your phone (at least happens on mine). I am not sure if it can be controlled anyhow, if you find any information about it, please share it here, and then I will try to elaborate. I will close this issue since I wouldn't consider it a bug. Feel free to comment if something is wrong.

**Comment by ArekChr** [comment]
This is not native behavior, this occur when I have polish characters in headers, when you have first screen scrolled to top position then should never be wrapped after go back to this screen from another.
of course if you have scrolled settings to bottom then shouldn't be never expanded but I have opposite case

**Comment by ArekChr** [comment]
![ezgif-7-e95cda1f7f6f](https://user-images.githubusercontent.com/24796318/92637912-cbd85980-f2d9-11ea-8e1f-6a3f290ea379.gif)
I don't think so this is also native behavior.
do you?

**Comment by WoLewicki** [comment]
If it happens in apps provided by Apple, and Settings is one of those apps, it should be called native behavior IMO. You can spot it in simulator with polish language enabled. And it is true that it looks related to the polish characters, as I said in the comment you linked. Why shouldn't it be scrolled though? If Apple wants such behavior, then using native navigation will behave accordingly. If you find any information about Apple stating it as a bug and a possible workaround for this, please provide it here. Otherwise, I am not sure if there can be anything done about it.
![polish-gif](https://user-images.githubusercontent.com/32481228/92695053-31632f00-f348-11ea-8e59-0300184a8dc7.gif)
