### ISSUE TITLE
2.12.0 (Android) createNativeStackNavigator "headerTitle" / "title" not displaying when "headerLeft" is set

### ISSUE THREAD

**Issue by jamsch** [software-mansion/react-native-screens#684]
Using v2.12.0, given the following example

```tsx
import { Text } from "react-native";
import { createNativeStackNavigator } from "react-native-screens/native-stack";

const DashboardStack = createNativeStackNavigator();

function DashboardStackView() {
  return (
    <DashboardStack.Navigator screenOptions={{ headerStyle: { backgroundColor: "#DC5E5C" } }}>
      <DashboardStack.Screen
        name="DashboardScreen"
        component={DashboardScreen}
        options={({ route }) => ({
          headerTitle: "Dashboard",
          headerLeft: () => <LeftDrawerButton />, // "() => null" also doesn't work
        })}
      />
    </DashboardStack.Navigator>
  );
}

const LeftDrawerButton = () => <Text>Drawer</Text>
```

Setting `headerTitle` or `title` doesn't seem to display at all when `headerLeft` is set.

![image](https://user-images.githubusercontent.com/12927717/97376709-f54d5300-1922-11eb-9a39-e92c0d491df2.png)

**Comment by WoLewicki** [comment]
It is the native behavior on Android since the title is on the left side of the header: https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerleft. Can I help you more with this?

**Comment by jamsch** [comment]
> It is the native behavior on Android since the title is on the left side of the header: https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerleft. Can I help you more with this?

Thanks for the link. Looks like that's a bit of a divergence from the `createStackNavigator` API meaning it won't be a simple drop-in replacement and there'll be a need for `Platform.OS` checks on client side code along with header text styling to achieve "left icon + text" on the top bar. May want to leave this issue open if there isn't one already.

**Comment by WoLewicki** [comment]
`createStackNavigator` API is not and should not be similar to the `createNativeStackNavigator` since, as the name suggests, `createNativeStackNavigator` uses native APIs of the platform, while `createStackNavigator` uses only JS to implement the parts of the e.g. header. We try to keep the `native-stack` options available for both platforms, but there will always be some APIs that don't exist on the other platform or work in another way there, and I think there is no escaping this.

**Comment by WoLewicki** [comment]
I am closing this issue then. If you have any questions, please comment here.

**Comment by darron1217** [comment]
@WoLewicki 
Then how about providing a way to override BackButton behavior?
All I wanted to do is overriding BackButton behavior, but I had to override `headerLeft` and it removed the title of screen :(

**Comment by darron1217** [comment]
Oh, I found a solution `navigation.addListener('beforeRemove', callback)`

**Comment by thunderclap1030** [comment]
Because it is the native behavior on Android since the title is on the left side of the header: https://github.com/software-mansion/react-native-screens/tree/master/native-stack#headerleft.

So you could use property `headerCenter` for show header title only for Android. That way will make sure consistent UI for both platform. 

For instance :

`headerCenter: () =>
          Platform.OS === 'android'  ? <Text> Home page </Text> : null`


I already try it and everything seem to be work well.
