### ISSUE TITLE
Video at top of react-native-screens' modal has controls offset

### ISSUE THREAD

**Issue by rmccue** [software-mansion/react-native-screens#785]
## Description

This is a cross-post of https://github.com/expo/expo/issues/11637 per @brentvatne's request; the bug happens somewhere in the interplay of expo-av and react-native-screens, but unclear exactly where.

Videos displayed at the top of a modal displayed via react-native-screens have controls offset from the top.

This offset appears to be adjusting for the status bar, however the modal presentation means this isn't required. This results in the controls appearing weirdly in the middle of the video.

Comparing this to when the stackPresentation is not set to `modal`, it appears that the offset appears to be adjusting for the safe area, but said adjustment isn't required when in the modal, as iOS' native modal display is offset naturally from the top of the screen.

### Screenshots

![Simulator Screen Shot - iPhone 11 - 2021-01-15 at 00 28 42](https://user-images.githubusercontent.com/21655/104665191-af558f00-56c8-11eb-8393-568d3fd7a5b2.png)

## Steps To Reproduce

The critical factors to cause this issue are:

* expo-av's Video
* Video rendered at the top of the screen
* Screen displayed in a react-native-screens modal; this doesn't occur in react-navigation's JS implementation of modals

The last condition indicates to me that this is probably an interplay of the native views with expo-av's Video.

This occurs in both native device and simulator.

### Expected behavior

The native video controls should render at the correct offset at the top of the video; i.e. y = 0, plus a bit of padding.

### Actual behavior

The controls instead appear ~30 pixels away from where they should.

## Snack or minimal code example

https://snack.expo.io/@rmccue/expo-av-native-stack-controls-bug

## Package versions

- React: 16.13.1
- React Native: Expo SDK 40.0.1 (RN 0.63.2)
- React Native Screens: 2.15.0 (via Expo and react-navigation)

**Comment by WoLewicki** [comment]
I tried the snack on physical iPhone SE 2020, and the bug is not there. Can you provide more information how/on which devices you tested this?

**Comment by rmccue** [comment]
@WoLewicki 🤦 I forgot the key piece of information here I guess, sorry about that! Tested this on both physical iPhone 11 Pro and simulator iPhone 11 devices. (I haven't tested this specific bug on notchless devices yet, oops)

Given you're not seeing it on a notchless device, I'd guess this is likely related to the safe area/notch offset?

**Comment by WoLewicki** [comment]
I checked this code with `Modal` component provided by `react-native` with `presentationStyle: "formsheet"`: https://snack.expo.io/N9BiTTcuH and it seems that the issue can be seen there too. I am afraid that it is not an issue related to `react-native-screens`, but rather the integration between `expo-av` and native iOS modals. It can be even a bug in the iOS. Having said this, I am afraid there is nothing to be done in `react-native-screens` about that issue since we do not manipulate these offsets. The thing that can be done if you have such an option is to check on a pure iOS project with similar configuration, if the issue is present there, then it is a bug in the native environment. Can you check and confirm my observations? Also, can I help you any more with this?

**Comment by rmccue** [comment]
Thanks for checking @WoLewicki. I have a corresponding issue filed in Expo for this (https://github.com/expo/expo/issues/11637) so I can take it back there. :)
