### ISSUE TITLE
Incorrect RNS behavior with RN Modal

### ISSUE THREAD

**Issue by JB1905** [software-mansion/react-native-screens#828]
## Description

Incorrect RNS behavior with RN Modal

### Screenshots

https://user-images.githubusercontent.com/28870390/108762142-05331780-7550-11eb-9729-4b1d1979d1f3.MP4

https://user-images.githubusercontent.com/28870390/108762156-082e0800-7550-11eb-8fcf-4cb5e1c799bf.MP4

## Snack or minimal code example

https://snack.expo.io/@jbiesiada/rns-modal-issue

## Package versions

- Expo SDK 40 (managed)
- React Native Screens: 2.15.2, 2.17.1

**Comment by WoLewicki** [comment]
RN modals cannot be used inside `react-native-screens` modals since, iirc, RN implementation make assumptions about the native view hierarchy structure that does not fit the `react-native-screens` implementation, causing bugs you posted. There is probably nothing we can do about it in `react-native-screens` unfortunately, but it is rather a field for changes in `react-native` implementation. Can I help you more with that?

**Comment by JB1905** [comment]
@WoLewicki thanks for reply
