### ISSUE TITLE
"RNSSearchBar" was not found in the UIManager (Expo project)

### ISSUE THREAD

**Issue by JB1905** [software-mansion/react-native-screens#928]
## Description

After adding `searchBar` to options I get the error:

```
Invariant Violation: requireNativeComponent: "RNSSearchBar" was not found in the UIManager.
```

<img src="https://user-images.githubusercontent.com/28870390/117706888-25c55200-b1ce-11eb-9410-2085f309a219.PNG" alt="IMG_5861" width="300" />

## Steps To Reproduce

1. Create Expo project with react-native-screens@3.2.0
2. Add `searchBar` config to stack screen

### Expected behavior

Configuration works fine

### Actual behavior

I'm getting error

## Package versions

- React: 16.13.1
- Expo: 41.0.1
- React Native Screens: 3.2.0

**Comment by kacperkapusciak** [comment]
Sadly, one of the disadvantages of Expo managed workflow is that you can't upgrade native dependencies by hand because they are compiled for a specific SDK. (See [this part](https://docs.expo.io/introduction/managed-vs-bare/#workflow-comparison) of Expo docs.) The newest version of  `react-native-screens` will be included (hopefully) in the next release of Expo SDK. I believe the current version of our lib in SDK 41 is v3.0.0. So, if you want to try out the newest version of `screens` you have to do it with a bare workflow.
Have a great day!

**Comment by phhoef** [comment]
I have the exact same problem, but unfortunately I am new to react native. @JB1905 could you please explain how you overcame this problem?

**Comment by JB1905** [comment]
@phhoef Please Upgrade Expo to version 42. If the error still exists, remove node_modules (and yarn.lock / package-lock.json if needed) and install packages. It works for me.

**Comment by phhoef** [comment]
Thanks, worked for me, too :-)
